<a href="https://colab.research.google.com/github/Aathavan05/DataScience-Notebooks/blob/main/3Feb2026_DataScience_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Create a dictionary of employee data
data = {
    'Employee_ID': [101, 102, 103, 104, 105, 106, 107],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Department': ['HR', 'IT', 'Finance', 'Marketing', 'IT', 'HR', 'Finance'],
    'Salary': [60000, 75000, 80000, 65000, 90000, 70000, 85000],
    'Hire_Date': ['2020-01-15', '2019-03-20', '2021-06-01', '2022-09-10', '2018-11-01', '2021-02-28', '2020-07-15']
}

# Create the DataFrame
df = pd.DataFrame(data)

# Convert 'Hire_Date' to datetime objects for better handling
df['Hire_Date'] = pd.to_datetime(df['Hire_Date'])

print("Original DataFrame:")
display(df)

Original DataFrame:

   Employee_ID     Name Department  Salary  Hire_Date
0          101    Alice         HR   60000 2020-01-15
1          102      Bob         IT   75000 2019-03-20
2          103  Charlie    Finance   80000 2021-06-01
3          104    David  Marketing   65000 2022-09-10
4          105      Eve         IT   90000 2018-11-01
5          106    Frank         HR   70000 2021-02-28
6          107    Grace    Finance   85000 2020-07-15

### Accessing Data with `.loc` (Label-based indexing)

`.loc` is primarily label-based, meaning you use row and column labels to select data. You can pass a single label, a list of labels, a slice of labels, or a boolean array.

In [ ]:
print("\nSelect row with index 2 using .loc:")
display(df.loc[2])

print("\nSelect rows with index 0, 3, and 5 using .loc:")
display(df.loc[[0, 3, 5]])

print("\nSelect rows from index 1 to 4 (inclusive) and 'Name' and 'Salary' columns using .loc:")
display(df.loc[1:4, ['Name', 'Salary']])

print("\nSelect employees in the 'IT' department using .loc with boolean indexing:")
display(df.loc[df['Department'] == 'IT'])

Select row with index 2 using .loc:

Employee_ID                    103
Name                       Charlie
Department                 Finance
Salary                       80000
Hire_Date      2021-06-01 00:00:00
Name: 2, dtype: object

Select rows with index 0, 3, and 5 using .loc:

   Employee_ID   Name Department  Salary  Hire_Date
0          101  Alice         HR   60000 2020-01-15
3          104  David  Marketing   65000 2022-09-10
5          106  Frank         HR   70000 2021-02-28

Select rows from index 1 to 4 (inclusive) and 'Name' and 'Salary' columns using .loc:

      Name  Salary
1      Bob   75000
2  Charlie   80000
3    David   65000
4      Eve   90000

Select employees in the 'IT' department using .loc with boolean indexing:

   Employee_ID Name Department  Salary  Hire_Date
1          102  Bob         IT   75000 2019-03-20
4          105  Eve         IT   90000 2018-11-01

### Accessing Data with `.iloc` (Integer-location based indexing)

`.iloc` is primarily integer-location based, meaning you use integer positions (from 0 to length-1) to select data. You can pass a single integer, a list of integers, or a slice of integers.

In [ ]:
print("\nSelect row at integer position 1 using .iloc:")
display(df.iloc[1])

print("\nSelect rows at integer positions 0, 2, and 4 using .iloc:")
display(df.iloc[[0, 2, 4]])

print("\nSelect rows from integer position 0 to 3 (exclusive) and columns from integer position 1 to 3 (exclusive) using .iloc:")
display(df.iloc[0:3, 1:3]) # Rows 0, 1, 2 and Columns 1 (Name), 2 (Department)

Select row at integer position 1 using .iloc:

Employee_ID                    102
Name                           Bob
Department                      IT
Salary                       75000
Hire_Date      2019-03-20 00:00:00
Name: 1, dtype: object

Select rows at integer positions 0, 2, and 4 using .iloc:

   Employee_ID     Name Department  Salary  Hire_Date
0          101    Alice         HR   60000 2020-01-15
2          103  Charlie    Finance   80000 2021-06-01
4          105      Eve         IT   90000 2018-11-01

Select rows from integer position 0 to 3 (exclusive) and columns from integer position 1 to 3 (exclusive) using .iloc:

      Name Department
0    Alice         HR
1      Bob         IT
2  Charlie    Finance

### Other Common DataFrame Operations

In [ ]:
print("\nSelecting a single column ('Name'):")
display(df['Name'])

print("\nSelecting multiple columns ('Name' and 'Salary'):")
display(df[['Name', 'Salary']])

print("\nFiltering rows based on a condition (Salary > 70000):")
display(df[df['Salary'] > 70000])

print("\nAdding a new column ('Bonus_Eligible' if Salary > 75000):")
df['Bonus_Eligible'] = df['Salary'] > 75000
display(df)

print("\nSorting the DataFrame by 'Salary' in descending order:")
display(df.sort_values(by='Salary', ascending=False))

print("\nGetting descriptive statistics for numerical columns:")
display(df.describe())

print("\nGetting information about the DataFrame (data types, non-null values):")
df.info()

Selecting a single column ('Name'):

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
Name: Name, dtype: object

Selecting multiple columns ('Name' and 'Salary'):

      Name  Salary
0    Alice   60000
1      Bob   75000
2  Charlie   80000
3    David   65000
4      Eve   90000
5    Frank   70000
6    Grace   85000

Filtering rows based on a condition (Salary > 70000):

   Employee_ID     Name Department  Salary  Hire_Date
1          102      Bob         IT   75000 2019-03-20
2          103  Charlie    Finance   80000 2021-06-01
4          105      Eve         IT   90000 2018-11-01
6          107    Grace    Finance   85000 2020-07-15

Adding a new column ('Bonus_Eligible' if Salary > 75000):

   Employee_ID     Name Department  Salary  Hire_Date  Bonus_Eligible
0          101    Alice         HR   60000 2020-01-15           False
1          102      Bob         IT   75000 2019-03-20           False
2          103  Charlie    Finance   80000 2021-06-01            True
3          104    David  Marketing   65000 2022-09-10           False
4          105      Eve         IT   90000 2018-11-01            True
5          106    Frank         HR   70000 2021-02-28           False
6          107    Grace    Finance   85000 2020-07-15            True

Sorting the DataFrame by 'Salary' in descending order:

   Employee_ID     Name Department  Salary  Hire_Date  Bonus_Eligible
4          105      Eve         IT   90000 2018-11-01            True
6          107    Grace    Finance   85000 2020-07-15            True
2          103  Charlie    Finance   80000 2021-06-01            True
1          102      Bob         IT   75000 2019-03-20           False
5          106    Frank         HR   70000 2021-02-28           False
3          104    David  Marketing   65000 2022-09-10           False
0          101    Alice         HR   60000 2020-01-15           False

Getting descriptive statistics for numerical columns:

       Employee_ID        Salary            Hire_Date
count     7.000000      7.000000                    7
mean    104.000000  75000.000000  2020-07-22 00:00:00
min     101.000000  60000.000000  2018-11-01 00:00:00
25%     102.500000  67500.000000  2019-08-17 12:00:00
50%     104.000000  75000.000000  2020-07-15 00:00:00
75%     105.500000  82500.000000  2021-04-15 12:00:00
max     107.000000  90000.000000  2022-09-10 00:00:00
std       2.160247  10801.234497                  NaN

Getting information about the DataFrame (data types, non-null values):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Employee_ID     7 non-null      int64
 1   Name            7 non-null      object
 2   Department      7 non-null      object
 3   Salary          7 non-null      int64
 4   Hire_Date       7 non-null      datetime64[ns]
 5   Bonus_Eligible  7 non-null      bool
dtypes: bool(1), datetime64[ns](1), int64(2), object(2)
memory usage: 419.0+ bytes

## Explanation of the Code:

1.  **Import pandas**: We start by importing the pandas library, which is essential for working with DataFrames. We typically alias it as `pd` for convenience.

    ```python
    import pandas as pd
    ```

2.  **Create Data**: We define a Python dictionary (`data`) where keys are column names and values are lists containing the data for each column. Each list must have the same length to form a rectangular DataFrame.

    ```python
    data = {
        'Employee_ID': [101, 102, 103, 104, 105, 106, 107],
        'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'IT', 'HR', 'Finance'],
        'Salary': [60000, 75000, 80000, 65000, 90000, 70000, 85000],
        'Hire_Date': ['2020-01-15', '2019-03-20', '2021-06-01', '2022-09-10', '2018-11-01', '2021-02-28', '2020-07-15']
    }
    ```

3.  **Create DataFrame**: We use `pd.DataFrame(data)` to convert our dictionary into a pandas DataFrame. By default, pandas assigns a numerical index starting from 0 to each row.

    ```python
    df = pd.DataFrame(data)
    ```

4.  **Convert 'Hire_Date'**: We convert the `Hire_Date` column from string type to datetime objects using `pd.to_datetime()`. This allows for easier date-based operations later.

    ```python
    df['Hire_Date'] = pd.to_datetime(df['Hire_Date'])
    ```

5.  **Display DataFrame**: `display(df)` shows the entire DataFrame, while `print()` is used for simple text output.

    ```python
    print("Original DataFrame:")
    display(df)
    ```

### Accessing Data with `.loc`:

*   **`df.loc[2]`**: Selects the row with the *label* (index) `2`. Since our index is numerical, it's the third row.
*   **`df.loc[[0, 3, 5]]`**: Selects multiple rows by providing a *list of labels* `[0, 3, 5]`.
*   **`df.loc[1:4, ['Name', 'Salary']]`**: Selects rows from label `1` up to and *including* label `4`, and only the columns labeled `'Name'` and `'Salary'`. For `.loc`, slices are inclusive for both rows and columns.
*   **`df.loc[df['Department'] == 'IT']`**: This is an example of **boolean indexing**. `df['Department'] == 'IT'` creates a Series of `True`/`False` values. `.loc` then uses this Series to select only the rows where the condition is `True` (i.e., department is 'IT').

### Accessing Data with `.iloc`:

*   **`df.iloc[1]`**: Selects the row at the *integer position* `1` (the second row, as Python indexing is 0-based).
*   **`df.iloc[[0, 2, 4]]`**: Selects multiple rows by providing a *list of integer positions* `[0, 2, 4]`.
*   **`df.iloc[0:3, 1:3]`**: Selects rows from integer position `0` up to (but *not including*) `3` (i.e., rows 0, 1, 2) and columns from integer position `1` up to (but *not including*) `3` (i.e., columns 1 and 2). For `.iloc`, slices are exclusive for the stop value, similar to standard Python list slicing.

### Other Common DataFrame Operations:

*   **`df['Name']`**: Selects a single column by its label, returning a pandas Series.
*   **`df[['Name', 'Salary']]`**: Selects multiple columns by providing a list of column labels, returning a new DataFrame.
*   **`df[df['Salary'] > 70000]`**: Filters rows based on a condition applied directly to the DataFrame. This is similar to boolean indexing with `.loc`.
*   **`df['Bonus_Eligible'] = df['Salary'] > 75000`**: Creates a new column named `Bonus_Eligible`. Its values are `True` if the employee's salary is greater than 75000, and `False` otherwise.
*   **`df.sort_values(by='Salary', ascending=False)`**: Sorts the DataFrame's rows based on the values in the `Salary` column in descending order.
*   **`df.describe()`**: Provides a quick statistical summary of the numerical columns in the DataFrame (count, mean, standard deviation, min, max, quartiles).
*   **`df.info()`**: Prints a concise summary of the DataFrame, including the index dtype, column dtypes, non-null values, and memory usage.